title: ClearStatus systems status page
languageCode: en
params:
  shortDateFormat: 15:04 — Jan 2
  meta_description: This status page provides updated information about our
    systems normal operation, incidents that may happen and their resolution.
  systems:
    - name: CovidSafe website
      description: Our public website
      link: https://covidsafeapp.com
    - name: Check In
      description: Our main product - Check In.
      link: https://checkin.covidsafeapp.com
  dateFormat: January 2, 2006 at 3:04 PM
  disqusShortname: null
  timezoneString: " Ireland/Dublin"
  logo: https://checkin.covidsafeapp.com/wp-content/uploads/2021/07/CovidSafe-Red-Icon.png
  description_header: Information about <a class='text-grey-darkest' title='Visit
    example.com' href='https://www.example.com/'>example</a> systems
    operations.<br />Follow us <a class='text-grey-darkest' title='Visit our
    page on Twitter' href='https://www.twitter.com/example'>on Twitter</a> or
    subscribe to <a class='text-grey-darkest' href='%s' >RSS</a><br />to be
    alerted of new events.
  copyrightHolder: CovidSafe
  eventsPerPage: 10
  iconType: image/png
  icon: /images/clearstatus.png
  description_footer: <a class='text-grey-darkest' title='Visit example.com'
    href='https://www.example.com/'>Example.com</a> provides open-source
    software for all kind of sectors.
